name: yearly analysis # name of my workflow 

on: 
  schedule: 
    - cron: "0 0 1 6 *" # triggers the workflow every year on the first of June at midnight; 0 0  (00:00 Midnight), 1 (first day of month), 6 (June), * (every year)

  push: 
    paths: 
      - 'Montserrat/data/**' # triggers a workflow every time a new file is added to the data folder in the repository
      
  workflow_dispatch:  # This allows manual triggering of the workflow
 
jobs: 
  build: # define a job
    runs-on: ubuntu-latest # set Environment for the job, here use windows as the virtual machine environment 

    steps: 
      - name: Checkout repository # provide a name for this step within the workflow
        uses: actions/checkout@v3

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        
      - name: Install Nim from git repository # Install Nim from git repository; needed for installation of NIMBLE 
        uses: iffy/install-nim@v5

      # - name: Install NIMBLE # actually install NIMBLE ###### THIS IS WHERE THE JOB FAILS ###### Could not find a file with a .nimble extension inside the specified directory: D:\a\Montserrat\Montserrat
      #   run: nimble install -y
        
      # - name: NIMBLE test # I'm not very sure what running 'nimble test' actually does 
        # run: nimble test

      - name: Install R dependencies 
        run: | 
          Rscript -e 'install.packages(c("ggplot2", "rmarkdown", "knitr", "remotes", "tidyverse", "data.table", "lubridate", "grid", "gtable", "reticulate", "splitstackshape", "RODBC",
            "dtplyr", "ggplot2", "MCMCvis", "nimble", "basicMCMCplots", "parallel", "foreach", "doParallel", "dplyr"))' 

          Rscript -e 'filter <- dplyr::filter; select <- dplyr::select; rename <- dplyr::rename'

      - name: Run data preparation and analyse point count data using N-mixture models for all species
        run: Rscript 'Montserrat_yearly_report_automated.R'
